### ISSUE TITLE
Problema na persistência dos dados

### ISSUE THREAD

**Issue by vicentecalfo** [Thamyresarm/react-UERJ#1]
Olá, Thamyres!

Tudo bem? Descobri o que estava errado com o código. Na verdade, o problema estava no arquivo .env.

Quando olhei a linha 3 do arquivo .env, percebi que você criou uma chave chamada "REACT_APP_PROTECTED_ID". Porém, ao conferir as atribuições de configuração no arquivo src/App.js, na linha 14, notei que você está procurando pela chave "REACT_APP_PROJECT_ID".

Para confirmar que esse era realmente o problema, fiz o clone do seu projeto e corrigi essa inconsistência. Agora está funcionando perfeitamente! Agora você só precisa ajustar isso para o seu "chat" funcionar!

Se tiver alguma dúvida, podemos esclarecê-la na próxima aula. Estou à disposição.

Até logo! 👋

**Comment by Thamyresarm** [comment]
Ahhh Obrigada Professor, vou corrigir aqui e testamos juntos em aula.

Até!
